import type { editor } from 'monaco-editor'

export const codeNestLightTheme: editor.IStandaloneThemeData = {
  base: 'vs',
  inherit: true,
  rules: [
    { token: 'comment',    foreground: '9ca3af', fontStyle: 'italic' },
    { token: 'keyword',    foreground: '7c3aed' },
    { token: 'string',     foreground: '16a34a' },
    { token: 'number',     foreground: 'ea580c' },
    { token: 'type',       foreground: '0284c7' },
    { token: 'function',   foreground: '2563eb' },
    { token: 'variable',   foreground: '0f172a' },
    { token: 'operator',   foreground: '4338ca' },
    { token: 'delimiter',  foreground: '6b7280' },
    { token: 'identifier', foreground: '0f172a' },
    { token: 'regexp',     foreground: 'db2777' },
    { token: 'tag',        foreground: 'dc2626' },
    { token: 'attribute',  foreground: 'd97706' },
  ],
  colors: {
    'editor.background':           '#f7faf4',
    'editor.foreground':           '#0f172a',
    'editorLineNumber.foreground': '#d1d5db',
    'editorLineNumber.activeForeground': '#9ca3af',
    'editor.selectionBackground':  '#6aa84f25',
    'editor.lineHighlightBackground': '#00000005',
    'editorCursor.foreground':     '#3d7a1c',
    'editorWhitespace.foreground': '#e2eadf',
    'editorIndentGuide.background1': '#e2eadf',
    'editorIndentGuide.activeBackground1': '#ccd9c8',
    'editor.findMatchBackground':  '#6aa84f30',
    'editor.findMatchHighlightBackground': '#6aa84f18',
    'editorBracketMatch.background': '#6aa84f20',
    'editorBracketMatch.border':   '#4a8a24',
    'scrollbarSlider.background':  '#00000010',
    'scrollbarSlider.hoverBackground': '#6aa84f30',
  },
}
