import type { editor } from 'monaco-editor'

export const codeNestDarkTheme: editor.IStandaloneThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: 'comment',    foreground: '6b7280', fontStyle: 'italic' },
    { token: 'keyword',    foreground: 'a78bfa' },
    { token: 'string',     foreground: '86efac' },
    { token: 'number',     foreground: 'fb923c' },
    { token: 'type',       foreground: '67e8f9' },
    { token: 'function',   foreground: '93c5fd' },
    { token: 'variable',   foreground: 'e2e8f0' },
    { token: 'operator',   foreground: 'a5b4fc' },
    { token: 'delimiter',  foreground: '9ca3af' },
    { token: 'identifier', foreground: 'e2e8f0' },
    { token: 'regexp',     foreground: 'f9a8d4' },
    { token: 'tag',        foreground: 'f87171' },
    { token: 'attribute',  foreground: 'fbbf24' },
  ],
  colors: {
    'editor.background':           '#0d120e',
    'editor.foreground':           '#e2e8f0',
    'editorLineNumber.foreground': '#374151',
    'editorLineNumber.activeForeground': '#6b7280',
    'editor.selectionBackground':  '#cbe89220',
    'editor.lineHighlightBackground': '#ffffff06',
    'editorCursor.foreground':     '#cbe892',
    'editorWhitespace.foreground': '#1a2318',
    'editorIndentGuide.background1': '#1a2318',
    'editorIndentGuide.activeBackground1': '#2d3d2a',
    'editor.findMatchBackground':  '#cbe89240',
    'editor.findMatchHighlightBackground': '#cbe89225',
    'editorBracketMatch.background': '#cbe89225',
    'editorBracketMatch.border':   '#cbe892',
    'scrollbarSlider.background':  '#ffffff10',
    'scrollbarSlider.hoverBackground': '#cbe89240',
  },
}
